### PR TITLE
Replace a few magic numbers

### PR DESCRIPTION
**Pull request by ddiss**
Use corresponding enum KEY_ACTION instead.

### CODE REVIEW

**Comment by Sonophoto** [comment]
Since you are making the code semantic aren't the comments redundant?

**Comment by Sonophoto** [comment]
Also: Where is KEY_ACTION defined? I've never used it.

**Comment by ddiss** [comment]
> Since you are making the code semantic aren't the comments redundant?

The redundant comments are already present elsewhere, so I decided to keep them here too.

> Also: Where is KEY_ACTION defined? I've never used it.

https://github.com/antirez/linenoise/blob/master/linenoise.c#L153

**Comment by ddiss** [comment]
Closing this - it seems that this project is no longer maintained upstream.

**Pull request closed without merging**
